# Site settings
title: Johnson
email: cnyjon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  《时代周刊》(Time) “2006年度风云人物”
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cnyjon.github.io" # the base hostname & protocol for your site
twitter_username: cnyjon
github_username:  cnyjon

# Build settings
markdown: kramdown
